name: Dart
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Install dependencies
        run: dart pub get
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze project source
        run: dart analyze
      - name: Compile and run sample program
        run: dart compile bin/chromos.dart && mv bin/chromos.exe . && mv chromos.exe chromos && chmod a+x chromos && ./chromos --version && ./chromos --help && ./chromos example/sample.chr
